### ISSUE TITLE
Type Aliases in type tests are incorrectly warned as always `true`/`false` when testing literal or local values

### ISSUE THREAD

**Issue by James-Ansley** [apple/pkl-intellij#9]
Given the following type alias:

```
typealias SillyString = String(this.startsWith("a") && this.length == 5)
```

The following RHS of the result expressions are all labelled with the warning `Expression is always 'false'` regardless of whether the value of the expression is true or false:

```
result1 = "abcde" is SillyString  // Expression is always 'false' (but is actually true)
result2 = "xyz" is SillyString  // Expression is always 'false' (and is actually false)

local value1 = "abcde"
result3 = value1 is SillyString  // Expression is always 'false' (but is actually true)
```

This doesn't happen with non-local names.

This gets flipped to `true` by default if creating a type alias with no type constraints:

```
typealias SillierString = SillyString
```

In this case, for example, `"xyz" is SillierString` is flagged as always being `true` when it is actually `false`.

I would expect that either:
- This warning didn't show up, or at least didn't show up in test cases. For example, I used `<thing> is <alias>` in several test cases, and the warnings here are unnecessary.
- This warning evaluated the correct value of `true`/`false` for the given expression.

**Comment by holzensp** [comment]
Ouch. Thanks for the report. I agree that it's better not to warn than to warn in the wrong direction. What is even stranger is that I would have expected the plugin to give up on `&&` (since constraints are arbitrary functions, the plugin can't/shouldn't evaluate them generally; it only checks a set of hardcoded functions). Independent of this bug report, I generally recommend using `,` instead of `&&` (if you don't have `||` making that semantically different) in constraints.

**Comment by James-Ansley** [comment]
Whoops! I missed "comma-separated list of type constraints" in the docs! Thanks for the tip. That doesn't change the behaviour described above, should it have?
